db:
  connectionProp: "{connectionString: 'http://localhost/8100-t-CS-test', userName: 'user-t-CS-test', password: 'pass-t-CS-test'}"
  host: localhost:8100t-CS-test
  port: 8100-test-CS-test
  
my:
    gretingMsg: hellot-CS-test
    list:
        values: onet,twot,threet,Four-CS-test  


  
