db:
  connectionProp: "{connectionString: 'http://localhost/8100-config-server', userName: 'user-cs', password: 'pass-cs'}"
  host: localhost:8100t
  port: 8100-test
  
my:
    gretingMsg: hellocs
    list:
        values: onet,twot,three,four-cs 
  
