db:
  connectionProp: "{connectionString: 'http://localhost/8100-t-CS-Cloud', userName: 'user-t-CS-Cloud', password: 'pass-t-CS-Cloud'}"
  host: localhost:8100t-CS-Cloud
  port: 8100-test-CS-Cloud
  
my:
    gretingMsg: hellot-CS-Cloud
    list:
        values: onet,twot,threet,Four-CS-Cloud  


  
